# Coverage-instrumented build of go-fdo-server, used only by go-fdo-ci's
# e2e coverage overlay. Mirrors go-fdo-server/Dockerfile's stages, but
# adds the GOFLAGS env var for enabling coverage instrumentation.
FROM golang:1.26-alpine AS builder

ARG GOFLAGS=""
ENV GOFLAGS=${GOFLAGS}

WORKDIR /go/src/app
COPY . .

RUN apk add --no-cache curl git gcc make musl-dev npm
RUN make build && install -D -m 755 go-fdo-server /go/bin/

FROM alpine

RUN apk add --no-cache tzdata curl libecpg

COPY --from=builder /go/bin/go-fdo-server /usr/bin/go-fdo-server

ENTRYPOINT ["go-fdo-server"]
CMD []
